import './globals.css';

export const metadata = {
  title: 'Carthage Bot',
  description: 'Generated by 7lib Bourgiba team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
